workspace 'JJiOSFramework.xcworkspace'

platform :ios, '7.0'

def shared_pods
    pod 'YTKNetwork', '~> 0.6.0'
    pod 'YYModel', '~> 0.9.8'
    pod 'SSKeychain', '~> 1.3.1'
end

target 'JJiOSFrameworkApp' do
    xcodeproj 'JJiOSFrameworkApp.xcodeproj'
    shared_pods
end
